kind: ConfigMap
apiVersion: v1
metadata:
  name: bench
  labels:
    app.kubernetes.io/name: bench
data:
  BENCH_URL: http://thanos-query.promstack.svc.cluster.local:9090/
  LOG: DEBUG
  BENCH_QUERIES_TOP5_PROM_HTTP_REQUESTS: topk by (code) (5, prometheus_http_requests_total)
  BENCH_QUERIES_COUNT_UP: count(up)
  BENCH_QUERIES_CPU_PER_POD: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (pod)
  BENCH_QUERIES_MIN_OVER_TIME__UP: min_over_time(count(up)[24h:1m])
  BENCH_QUERIES_UNAVAILABLE_APISERVICE: (1 - max by (name, namespace, cluster) (avg_over_time(aggregator_unavailable_apiservice[10m]))) * 100 < 85
  BENCH_QUERIES_MEMORY_USAGE: sum(container_memory_rss{job="kubelet", container!=""}) by (namespace)
  BENCH_QUERIES_NGINX: |
    histogram_quantile(
      0.5,
      sum by (le)(
        rate(
          nginx_ingress_controller_request_duration_seconds_bucket{
            ingress =~ ".*"
          }[5m]
        )
      )
    )
  BENCH_QUERIES_FREE_PVC_SPACE: |
    (
      sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{job="kubelet"})))
      -
      sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{job="kubelet"})))
    )
