apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bench
  name: bench
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bench
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bench
    spec:
      containers:
      - image: kbudde/bench-metrics:latest
        imagePullPolicy: Always
        name: bench-metrics
        envFrom:
          - configMapRef:
              name: bench
        ports:
          - name: metrics
            containerPort: 9898
            protocol: TCP
        resources: 
          requests:
            cpu: 50m
            memory: 500Mi
          limits:
            memory: 550Mi