apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bench
  labels:
    app.kubernetes.io/name: bench
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: bench
