apiVersion: v1
kind: Service
metadata:
  name: bench
  labels:
    app.kubernetes.io/name: bench
spec:
  selector:
    app.kubernetes.io/name: bench
  ports:
  - name: metrics
    protocol: TCP
    port:  9898
    targetPort: 9898
