name: build

on:
  push:
    branches: [ "main", "action" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt -- --check
    - name: clippy
      run: cargo clippy -- -Dwarnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t kbudde/bench-metrics:${{ github.sha }} .
          docker tag kbudde/bench-metrics:${{ github.sha }} kbudde/bench-metrics:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push kbudde/bench-metrics:${{ github.sha }}
          docker push kbudde/bench-metrics:latest